# Generated by Django 4.1.2 on 2022-12-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsletter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
