# Generated by Django 4.1.2 on 2022-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='loremipsum', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BuildPackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='loremipsum', max_length=250)),
                ('storage', models.CharField(default='20', max_length=10)),
                ('lifetimesupport', models.BooleanField(default=False)),
                ('premiumaddons', models.BooleanField(default=False)),
                ('fastestnetwork', models.BooleanField(default=False)),
                ('moreoptions', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='build-packets')),
                ('price', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='loremipsum', max_length=250)),
                ('image', models.ImageField(upload_to='products')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='loremipsum', max_length=100)),
                ('description', models.CharField(default='loremipsum', max_length=250)),
                ('image', models.ImageField(upload_to='products')),
                ('url', models.URLField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='loremipsum', max_length=250)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
